/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Account model representing clients.
type Account struct {

	// Id of account (client)
	Id int32 `json:"Id,omitempty"`

	// Account addressess
	Addresses []Address `json:"Addresses,omitempty"`

	// Payment information
	Payment *PaymentDetails `json:"Payment,omitempty"`

	// Company information for company account
	Company *CompanyDetails `json:"Company,omitempty"`

	// Is Freemium enabled for account
	FreemiumEnabled bool `json:"FreemiumEnabled,omitempty"`
}
