/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

type ApiCollectionSubregion struct {
	Items []Subregion `json:"Items,omitempty"`

	Meta *ApiCollectionMetadata `json:"Meta,omitempty"`
}
