/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Assign new monitoring sensor command
type AssignNewMonitoringSensorCommand struct {

	// Sensor id
	SensorId int32 `json:"SensorId"`
}
