/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Assign new IP to client command
type BookIpCommand struct {

	// Subregion Id
	SubregionId int32 `json:"SubregionId"`
}
