/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Change disk tier command
type ChangeDiskTierCommand struct {

	// Tier id
	TierId int32 `json:"TierId"`
}
