/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Change instance type command
type ChangeInstanceTypeCommand struct {

	// Type id
	TypeId int32 `json:"TypeId"`
}
