/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Change instance subregion command
type ChangeInstanceSubregionCommand struct {

	// Subregion Id
	SubregionId int32 `json:"SubregionId,omitempty"`
}
