/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Change Ip address subregion command
type ChangeFloatingIpSubregionCommand struct {

	// IPv4 address identifier.
	IpV4 string `json:"IpV4"`

	// Subregion Id
	SubregionId int32 `json:"SubregionId,omitempty"`
}
