/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Change OPN command
type ChangeOpnCommand struct {

	// Target OPN id
	TargetOpnId int32 `json:"TargetOpnId"`

	// Interface id
	InterfaceId int32 `json:"InterfaceId"`
}
