/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Change hot plug setting command
type ChangeHotPlugSettingCommand struct {

	// Is hot plug enabled
	HotPlugEnabled bool `json:"HotPlugEnabled"`
}
