/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Change instance name commnad
type ChangeInstanceNameCommand struct {

	// Name of an instance
	Name string `json:"Name"`
}
