/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Change Ip address subregion command
type ChangeIpSubregionCommand struct {

	// IP address identifier
	IpId int32 `json:"IpId"`

	// Subregion Id
	SubregionId int32 `json:"SubregionId,omitempty"`
}
