/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

import (
	"time"
)

// Client statistics
type ClientStatistics struct {

	// Statistic type
	StatisticType *BaseResource `json:"StatisticType,omitempty"`

	// Sample time
	SampleTime time.Time `json:"SampleTime,omitempty"`

	// Value
	Value int64 `json:"Value,omitempty"`
}
