/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Company information
type CompanyDetails struct {

	// Company id
	Id int32 `json:"Id,omitempty"`

	// Name
	Name string `json:"Name,omitempty"`

	// Nip
	Nip string `json:"Nip,omitempty"`

	// Regon
	Regon string `json:"Regon,omitempty"`

	// Krs
	Krs string `json:"Krs,omitempty"`

	// Email
	Email string `json:"Email,omitempty"`

	// Phone
	Phone string `json:"Phone,omitempty"`
}
