/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Container assignment
type ContainerAssignmentCommand struct {

	// Id of an instance
	InstanceId int32 `json:"InstanceId"`

	// Ip address for load balancer
	IpId int32 `json:"IpId"`
}
