/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

import (
	"time"
)

// Create group scheduler command
type CreateUpdateGroupSchedulerCommand struct {

	// Scheduler name
	Name string `json:"Name"`

	// Start date
	StartDate time.Time `json:"StartDate"`

	// IANA Time zone. To get a list of available timezones, visit (https://momentjs.com/timezone)
	TimeZoneName string `json:"TimeZoneName"`

	// Instance Id
	InstanceId int32 `json:"InstanceId"`

	// Action type id
	ActionTypeId int32 `json:"ActionTypeId"`

	// Scheduler type id
	SchedulerTypeId int32 `json:"SchedulerTypeId"`

	// Cycle type id
	CycleTypeId int32 `json:"CycleTypeId,omitempty"`

	// Cycle number
	CycleNumber int32 `json:"CycleNumber,omitempty"`
}
