/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Create/update VNC connection command
type CreateUpdateVncConnectionCommand struct {

	// Source ip - only connections from this source ip will be accepted
	SourceIp string `json:"SourceIp,omitempty"`

	// Connection will be closed after that period
	TimeoutInMinutes int32 `json:"TimeoutInMinutes"`
}
