/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Create/update ping health check command
type CreateUpdateHealthCheckPingCommand struct {

	// Data package size [bytes]
	PackageSize int32 `json:"PackageSize"`

	// Maximum waiting time for a response [ms]
	ReplyTimeout int32 `json:"ReplyTimeout"`

	// How many (%) locations have to report an error to consider it a breakdown
	ErrorTolerance int32 `json:"ErrorTolerance"`

	// Health check name
	Name string `json:"Name"`

	// URL or IP address of the monitored service
	Address string `json:"Address"`

	// Time interval between health checks, in seconds
	Interval int32 `json:"Interval"`

	// Is paused
	Paused bool `json:"Paused"`

	// Use random substitute locations in case of location breakdown
	LocationsFailoverEnabled bool `json:"LocationsFailoverEnabled"`

	// Notification types enabled for a health check
	NotificationTypeIds []int32 `json:"NotificationTypeIds,omitempty"`

	// Event types with enabled notification
	NotificationEventTypeIds []int32 `json:"NotificationEventTypeIds,omitempty"`

	// Time when notification is sent
	NotificationTimeId int32 `json:"NotificationTimeId"`
}
