/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Create instance command
type CreateInstanceCommand struct {

	// Authorization method (Password)
	AuthorizationMethodId int32 `json:"AuthorizationMethodId,omitempty"`

	// Class of disk
	DiskClass int32 `json:"DiskClass,omitempty"`

	// Size of disk in gigabytes
	DiskSize int32 `json:"DiskSize,omitempty"`

	// Name of an instance
	InstanceName string `json:"InstanceName"`

	// Count of instances
	InstancesCount int32 `json:"InstancesCount,omitempty"`

	// Id of ip address
	IPAddressId int32 `json:"IPAddressId,omitempty"`

	// Id of ssh keys to be attached to the instance
	SshKeysIds []int32 `json:"SshKeysIds,omitempty"`

	// Id of opns where attach the instance
	OpnsIds []int32 `json:"OpnsIds,omitempty"`

	// Id of target subregion
	SubregionId int32 `json:"SubregionId,omitempty"`

	// Template id
	TemplateId int32 `json:"TemplateId"`

	// Type of an instance
	TypeId int32 `json:"TypeId,omitempty"`

	// Freemium
	Freemium bool `json:"Freemium,omitempty"`

	// InitScript
	InitScript string `json:"InitScript,omitempty"`

	// WithoutPublicIp
	WithoutPublicIp bool `json:"WithoutPublicIp,omitempty"`
}
