/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Create/update snapshot command
type CreateUpdateSnapshotCommand struct {

	// Name
	Name string `json:"Name"`

	// Description
	Description string `json:"Description,omitempty"`
}
