/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

import (
	"time"
)

// Delete events command
type DeleteEventsCommand struct {

	// Date from
	DateFrom time.Time `json:"DateFrom"`

	// Date to
	DateTo time.Time `json:"DateTo"`
}
