/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Delet snapshots command
type DeleteSnapshotsCommand struct {

	// Ids
	Ids []int32 `json:"Ids"`
}
