/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Detach IP from instance command
type DetachFloatingIpFromInstanceCommand struct {

	// IPv4 address identifier
	IpV4 string `json:"IpV4"`

	// Instance identifier.
	InstanceId int32 `json:"InstanceId"`
}
