/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Detach instance from OPN command
type DetachInstanceFromOpnCommand struct {

	// OPN id
	OpnId int32 `json:"OpnId"`
}
