/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Detach IP from instance command
type DetachIpFromInstanceCommand struct {

	// IP address identifier
	IpId int32 `json:"IpId"`
}
