/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Dictionary item
type DictionaryItem struct {

	// ID
	Id int32 `json:"Id,omitempty"`

	// Label
	Label string `json:"Label,omitempty"`

	// Dictionary
	Dictionary *Resource `json:"Dictionary,omitempty"`
}
