/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Dictionary
type Dictionary struct {

	// Id
	Id int32 `json:"Id,omitempty"`

	// Name
	Name string `json:"Name,omitempty"`
}
