/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

import (
	"time"
)

// OVS disk
type Disk struct {

	// Id
	Id int32 `json:"Id,omitempty"`

	// Name
	Name string `json:"Name,omitempty"`

	// Space capacity in GB
	SpaceCapacity int32 `json:"SpaceCapacity,omitempty"`

	// Tier
	Tier *DictionaryItem `json:"Tier,omitempty"`

	// Creation date
	CreationDate time.Time `json:"CreationDate,omitempty"`

	// User who created the disk
	CreationUser *UserResource `json:"CreationUser,omitempty"`

	// If disk is shared
	IsShared bool `json:"IsShared,omitempty"`

	// Shared disk type, null if disk is not shared
	SharedDiskType *DictionaryItem `json:"SharedDiskType,omitempty"`

	// Subregion
	Subregion *BaseResource `json:"Subregion,omitempty"`

	// If the disk is locked by a running operation
	IsLocked bool `json:"IsLocked,omitempty"`

	// Locking date
	LockingDate time.Time `json:"LockingDate,omitempty"`

	// Connections to instances
	Connections []DiskConnection `json:"Connections,omitempty"`

	// Is freemium
	IsFreemium bool `json:"IsFreemium,omitempty"`
}
