/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Represents disk connection to instance
type DiskConnection struct {

	// Instance
	Instance *BaseResource `json:"Instance,omitempty"`

	// Controller
	Controller int32 `json:"Controller,omitempty"`

	// Slot
	Slot int32 `json:"Slot,omitempty"`

	// If is system disk
	IsSystemDisk bool `json:"IsSystemDisk,omitempty"`
}
