/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

import (
	"time"
)

// Search params for instance events
type EventsSearchParams struct {

	// User id
	UserId int32 `json:"UserId,omitempty"`

	// Date from
	DateFrom time.Time `json:"DateFrom,omitempty"`

	// Date to
	DateTo time.Time `json:"DateTo,omitempty"`

	// Operation type id
	OperationTypeId int32 `json:"OperationTypeId,omitempty"`

	// Page size
	PageSize int32 `json:"PageSize,omitempty"`

	// Page number
	PageNumber int32 `json:"PageNumber,omitempty"`

	// Order by
	OrderBy string `json:"OrderBy,omitempty"`

	// Sort expression
	SortExpression string `json:"SortExpression,omitempty"`

	// Sort direction
	SortDirection string `json:"SortDirection,omitempty"`
}
