/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

import (
	"time"
)

// Instance export task
type Export struct {

	// Id
	Id int32 `json:"Id,omitempty"`

	// Name
	Name string `json:"Name,omitempty"`

	// Creation date
	CreationDate time.Time `json:"CreationDate,omitempty"`

	// Start date
	StartDate time.Time `json:"StartDate,omitempty"`

	// End date
	EndDate time.Time `json:"EndDate,omitempty"`

	// Status
	Status *DictionaryItem `json:"Status,omitempty"`

	// Location in OCS
	OcsLocation string `json:"OcsLocation,omitempty"`

	// OCS Project Id
	OcsProjectId string `json:"OcsProjectId,omitempty"`

	// Total space capacity in GB
	TotalSpaceCapacity int32 `json:"TotalSpaceCapacity,omitempty"`

	// Instance
	Instance *NamedResource `json:"Instance,omitempty"`

	// Creation user
	CreationUser *UserResource `json:"CreationUser,omitempty"`

	// Origin
	Origin *DictionaryItem `json:"Origin,omitempty"`

	// Scheduler that launches export
	Scheduler *BaseResource `json:"Scheduler,omitempty"`
}
