/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Get screenshot command
type GetScreenshotCommand struct {

	// The pixel width of the scaled image
	Width int32 `json:"Width,omitempty"`

	// The pixel height of the scaled image
	Height int32 `json:"Height,omitempty"`
}
