/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

import (
	"time"
)

// Group
type Group struct {

	// Id
	Id int32 `json:"Id,omitempty"`

	// Name
	Name string `json:"Name,omitempty"`

	// Is load balancing enabled
	IsLoadBalancer bool `json:"IsLoadBalancer,omitempty"`

	// Instances count in container
	InstancesCount int32 `json:"InstancesCount,omitempty"`

	// Schedulers count assigned to container
	SchedulersCount int32 `json:"SchedulersCount,omitempty"`

	// Instances affinity rule type
	AffinityRuleType *DictionaryItem `json:"AffinityRuleType,omitempty"`

	// Autoscaling type
	AutoscalingType *DictionaryItem `json:"AutoscalingType,omitempty"`

	// Last modified date
	LastChangeDate time.Time `json:"LastChangeDate,omitempty"`

	// User who created the group
	CreationUser *UserResource `json:"CreationUser,omitempty"`
}
