/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

import (
	"time"
)

// Group scheduler
type GroupScheduler struct {

	// ID
	Id int32 `json:"Id,omitempty"`

	// User who created the scheduler
	CreationUser *UserResource `json:"CreationUser,omitempty"`

	// Instance
	Instance *BaseResource `json:"Instance,omitempty"`

	// Group
	Group *BaseResource `json:"Group,omitempty"`

	// Creation date
	CreationDate time.Time `json:"CreationDate,omitempty"`

	// Last change date
	LastChangeDate time.Time `json:"LastChangeDate,omitempty"`

	// Start date
	StartDate time.Time `json:"StartDate,omitempty"`

	// Time zone name
	TimeZoneName string `json:"TimeZoneName,omitempty"`

	// Scheduler name
	Name string `json:"Name,omitempty"`

	// Status
	Status *DictionaryItem `json:"Status,omitempty"`

	// Type
	Type_ *DictionaryItem `json:"Type,omitempty"`

	// Action type
	ActionType *DictionaryItem `json:"ActionType,omitempty"`

	// Cycle type
	CycleType *DictionaryItem `json:"CycleType,omitempty"`

	// Cycle number beetwen scheduler launch
	CycleNumber int32 `json:"CycleNumber,omitempty"`
}
