/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Instance used by group autoscaler
type GroupAutoscalerInstance struct {

	// Instance
	Instance *BaseResource `json:"Instance,omitempty"`

	// Order number
	OrderNumber int32 `json:"OrderNumber,omitempty"`
}
