/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Disk of imported OCI
type ImportDisk struct {

	// Id of disk
	Id int32 `json:"Id,omitempty"`

	// Capacity in GB
	Capacity int32 `json:"Capacity,omitempty"`

	// Disk name
	DiskName string `json:"DiskName,omitempty"`

	// Relative path
	RelativePath string `json:"RelativePath,omitempty"`

	// Controller index
	Controller int32 `json:"Controller,omitempty"`

	// Controller slot index
	ControllerSlot int32 `json:"ControllerSlot,omitempty"`
}
