/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Instance type
type InstanceType struct {

	// Id
	Id int32 `json:"Id,omitempty"`

	// Name
	Name string `json:"Name,omitempty"`

	// Number of CPU
	Cpu int32 `json:"Cpu,omitempty"`

	// Memory in MB
	Ram int32 `json:"Ram,omitempty"`

	// Is available for Freemiuim
	AvailableForFreemium bool `json:"AvailableForFreemium,omitempty"`

	// Category
	Category *DictionaryItem `json:"Category,omitempty"`
}
