/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

import (
	"time"
)

// Event that have occurred on instance
type InstanceEvent struct {

	// Id
	Id int64 `json:"Id,omitempty"`

	// Date
	Date time.Time `json:"Date,omitempty"`

	// Instance
	Instance *NamedResource `json:"Instance,omitempty"`

	// User who performed the operation
	User *UserResource `json:"User,omitempty"`

	// Operation type
	OperationType *DictionaryItem `json:"OperationType,omitempty"`

	// Operation status
	OperationStatus *DictionaryItem `json:"OperationStatus,omitempty"`

	// Message
	Message string `json:"Message,omitempty"`
}
