/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// HATEOAS link
type Link struct {

	Rel string `json:"Rel,omitempty"`

	Href string `json:"Href,omitempty"`
}
