/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Load balancer server
type LoadBalancerServer struct {

	// Ip address
	IpAddress string `json:"IpAddress,omitempty"`

	// Port
	Port int32 `json:"Port,omitempty"`

	// Protocol
	Protocol string `json:"Protocol,omitempty"`

	// Active services. Null if HealthCheckEnabled in Load balancer disabled.
	ActiveServices int64 `json:"ActiveServices,omitempty"`

	// Inactive services. Null if HealthCheckEnabled in Load balancer disabled.
	InactiveServices int64 `json:"InactiveServices,omitempty"`

	// Request rate
	RequestRate int64 `json:"RequestRate,omitempty"`

	// Response rate
	ResponseRate int64 `json:"ResponseRate,omitempty"`

	// Request rate in bytes
	RequestRateBytes int64 `json:"RequestRateBytes,omitempty"`

	// Response rate in bytes
	ResponseRateBytes int64 `json:"ResponseRateBytes,omitempty"`

	// Current client connections
	CurrentClientConnections int64 `json:"CurrentClientConnections,omitempty"`

	// Status
	Status *DictionaryItem `json:"Status,omitempty"`

	// Services statistics. Filled only in load balancer details.
	Services []LoadBalancerService `json:"Services,omitempty"`
}
