/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Load balancer
type LoadBalancer struct {

	// Group id
	GroupId int32 `json:"GroupId,omitempty"`

	// Group name
	GroupName string `json:"GroupName,omitempty"`

	// IPv4 address
	IpAddress string `json:"IpAddress,omitempty"`

	// IPv6 address
	IpV6Address string `json:"IpV6Address,omitempty"`

	// Service type (HTTP, SMTP, Port...)
	ServiceType *DictionaryItem `json:"ServiceType,omitempty"`

	// Port number for \"Port\" service type
	PortNumber int32 `json:"PortNumber,omitempty"`

	// Port number for \"TargetPort\" service type
	TargetPortNumber int32 `json:"TargetPortNumber,omitempty"`

	// Ssl port number for \"TargetPort\" service type
	SslTargetPortNumber int32 `json:"SslTargetPortNumber,omitempty"`

	// Session persistence type
	SessionPersistenceType *DictionaryItem `json:"SessionPersistenceType,omitempty"`

	// Algorithm
	Algorithm *DictionaryItem `json:"Algorithm,omitempty"`

	// IP version
	IpVersion *DictionaryItem `json:"IpVersion,omitempty"`

	// Is health check enabled
	HealthCheckEnabled bool `json:"HealthCheckEnabled,omitempty"`

	// Is ssl enabled (only for \"HTTP\" service type)
	SslEnabled bool `json:"SslEnabled,omitempty"`

	// Is common persistence for HTTP and HTTPS enabled (only for \"HTTP\" service type)
	CommonPersistenceForHttpAndHttpsEnabled bool `json:"CommonPersistenceForHttpAndHttpsEnabled,omitempty"`

	// Services
	Servers []LoadBalancerServer `json:"Servers,omitempty"`
}
