/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Network interface
type NetworkInterface struct {

	// Interface id
	InterfaceId int32 `json:"InterfaceId,omitempty"`

	// The MAC address of the network card associated with that IP address
	MacAddress string `json:"MacAddress,omitempty"`

	// Instance
	Instance *NamedResource `json:"Instance,omitempty"`

	// OPN
	Opn *NamedResource `json:"Opn,omitempty"`

	// IP address version 4
	Address string `json:"Address,omitempty"`

	// IP address version 6
	AddressV6 string `json:"AddressV6,omitempty"`

	// IP address
	Ip *BaseResource `json:"Ip,omitempty"`

	// Comment
	Comment string `json:"Comment,omitempty"`

	// RevDNS
	RevDns string `json:"RevDns,omitempty"`

	// RevDNS v6
	RevDnsV6 string `json:"RevDnsV6,omitempty"`

	// Subregion
	Subregion *BaseResource `json:"Subregion,omitempty"`

	// User who created the network interface
	CreationUser *UserResource `json:"CreationUser,omitempty"`
}
