/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

type NullableTime struct {

	// Hours
	Hours int32 `json:"Hours,omitempty"`

	// Minutes
	Minutes int32 `json:"Minutes,omitempty"`
}
