/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Oktawave Cloud Storage Project
type OcsProject struct {

	// ID
	Id string `json:"Id,omitempty"`

	// Name
	Name string `json:"Name,omitempty"`

	// Description
	Description string `json:"Description,omitempty"`

	// Url
	Url string `json:"Url,omitempty"`

	// Authorization type
	AuthorizationType *DictionaryItem `json:"AuthorizationType,omitempty"`
}
