/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

import (
	"time"
)

// Virtual private network
type Opn struct {

	// ID
	Id int32 `json:"Id,omitempty"`

	// Name
	Name string `json:"Name,omitempty"`

	// Creation date
	CreationDate time.Time `json:"CreationDate,omitempty"`

	// Last change date
	LastChangeDate time.Time `json:"LastChangeDate,omitempty"`

	// User who created the opn
	CreationUser *UserResource `json:"CreationUser,omitempty"`

	// Private IPs
	PrivateIps []PrivateIp `json:"PrivateIps,omitempty"`
}
