/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Payment information
type PaymentDetails struct {

	// Account number
	AccountNumber string `json:"AccountNumber,omitempty"`

	// External account number
	ExternalAccountNumber string `json:"ExternalAccountNumber,omitempty"`

	// Payment method
	PaymentMethod *DictionaryItem `json:"PaymentMethod,omitempty"`

	// Vat rate
	VatRate float64 `json:"VatRate,omitempty"`
}
