/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Run import disk command
type RunImportDiskCommand struct {

	// Id of an imported disk
	ImportDiskId int32 `json:"ImportDiskId"`

	// Tier id
	TierId int32 `json:"TierId"`
}
