/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Run import command
type RunImportCommand struct {

	// Id of target subregion
	SubregionId int32 `json:"SubregionId,omitempty"`

	// Type of an instance
	TypeId int32 `json:"TypeId"`

	// Disks specification
	Disks []RunImportDiskCommand `json:"Disks"`

	// Network specification
	Network []RunImportNetworkCommand `json:"Network"`
}
