/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Set container autoscaler
type SetGroupAutoscalerCommand struct {

	// Expansion type
	ExpansionTypeId int32 `json:"ExpansionTypeId"`

	// Minimum instance number in container
	MinimumInstanceNumber int32 `json:"MinimumInstanceNumber"`

	// Minimum instance number in container
	MaximumInstanceNumber int32 `json:"MaximumInstanceNumber"`

	// Instances to scaling
	Instances []GroupAutoscalerInstance `json:"Instances"`
}
