/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Set load balancer command
type SetLoadBalancerCommand struct {

	// Is ssl enabled (only for \"HTTP\" load balancer service type)
	SslEnabled bool `json:"SslEnabled,omitempty"`

	// Load balancer service type
	ServiceType int32 `json:"ServiceType"`

	// Port number for \"Port\" load balancer service type
	PortNumber int32 `json:"PortNumber,omitempty"`

	// Port number for \"TargetPort\" load balancer service type
	TargetPortNumber int32 `json:"TargetPortNumber,omitempty"`

	// Ssl port number for \"TargetPort\" load balancer service type
	SslTargetPortNumber int32 `json:"SslTargetPortNumber,omitempty"`

	// Session persistence type
	SessionPersistenceType int32 `json:"SessionPersistenceType"`

	// Load balancing algorithm
	LoadBalancerAlgorithm int32 `json:"LoadBalancerAlgorithm"`

	// Ip version for load balancing
	IpVersion int32 `json:"IpVersion"`

	// Is health check enabled
	HealthCheckEnabled bool `json:"HealthCheckEnabled,omitempty"`

	// Is common persistence for HTTP and HTTPS enabled (only for \"HTTP\" load balancer service type)
	CommonPersistenceForHttpAndHttpsEnabled bool `json:"CommonPersistenceForHttpAndHttpsEnabled,omitempty"`

	// Public ip id for load balancer
	LoadBalancerIpId int32 `json:"LoadBalancerIpId,omitempty"`
}
