/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

import (
	"time"
)

// Snapshot
type Snapshot struct {

	// ID
	Id int32 `json:"Id,omitempty"`

	// Name
	Name string `json:"Name,omitempty"`

	// Description
	Description string `json:"Description,omitempty"`

	// Instance
	Instance *BaseResource `json:"Instance,omitempty"`

	// Creation date
	CreationDate time.Time `json:"CreationDate,omitempty"`

	// Last change date
	LastChangeDate time.Time `json:"LastChangeDate,omitempty"`

	// User who created the snapshot
	CreationUser *UserResource `json:"CreationUser,omitempty"`

	// Is system snapshot. Not created by the user.
	IsSystem bool `json:"IsSystem,omitempty"`

	// Is current
	IsCurrent bool `json:"IsCurrent,omitempty"`

	// Snapshot parent
	SnapshotParent *BaseResource `json:"SnapshotParent,omitempty"`
}
