/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Template description
type TemplateDescription struct {

	// Language id
	LanguageId int32 `json:"LanguageId"`

	// Description
	Description string `json:"Description"`
}
