/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

import (
	"time"
)

// Template
type Template struct {

	// Id
	Id int32 `json:"Id,omitempty"`

	// Name
	Name string `json:"Name,omitempty"`

	// Description
	Description string `json:"Description,omitempty"`

	// Version
	Version string `json:"Version,omitempty"`

	// Creation date
	CreationDate time.Time `json:"CreationDate,omitempty"`

	// Last change date
	LastChangeDate time.Time `json:"LastChangeDate,omitempty"`

	// User who created the template
	CreationUser *UserResource `json:"CreationUser,omitempty"`

	// Default instance type
	DefaultInstanceType *DictionaryItem `json:"DefaultInstanceType,omitempty"`

	// Minimum instance type
	MinimumInstanceType *DictionaryItem `json:"MinimumInstanceType,omitempty"`

	// Ethernet controllers number
	EthernetControllersNumber int32 `json:"EthernetControllersNumber,omitempty"`

	// Ethernet controllers type
	EthernetControllersType *DictionaryItem `json:"EthernetControllersType,omitempty"`

	// System category
	SystemCategory *DictionaryItem `json:"SystemCategory,omitempty"`

	// Owner account
	OwnerAccount *BaseResource `json:"OwnerAccount,omitempty"`

	// Publication status
	PublicationStatus *DictionaryItem `json:"PublicationStatus,omitempty"`

	// Disks
	Disks []TemplateDisk `json:"Disks,omitempty"`

	// Softwares
	Software []Software `json:"Software,omitempty"`

	// Template type
	TemplateType *DictionaryItem `json:"TemplateType,omitempty"`
}
