/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Icon file
type TemplateIcon struct {

	// File name
	FileName string `json:"FileName"`

	// File source in Base64
	FileSource string `json:"FileSource"`
}
