/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Update template command
type UpdateTemplateCommand struct {

	// Template name
	Name string `json:"Name,omitempty"`

	// Template descriptions
	TemplateDescriptions []TemplateDescription `json:"TemplateDescriptions,omitempty"`
}
