/*
 * Oktawave API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package odk

// Update disk command
type UpdateDiskCommand struct {

	// Name of disk
	DiskName string `json:"DiskName"`

	// Space capacity in GB
	SpaceCapacity int32 `json:"SpaceCapacity"`

	// Tier id
	TierId int32 `json:"TierId"`

	// Subregion identifier
	SubregionId int32 `json:"SubregionId"`

	// Instance ids list
	InstanceIdsList []int32 `json:"InstanceIdsList,omitempty"`
}
